---
- name: started and enabled nginx
  service:
   name: nginx
   state: started
   enabled: yes
  
- name: remove older Nginx Config
  file:
   path: /etc/nginx
   state: absent
    
- name: clone new Nginx config
  git:
   repo: https://github.com/MAELUP/backend-lb-dev.git
   dest: /etc/nginx
    
- name: restart nginx
  service:
   name:  nginx
   state: restarted

- name: open service port_80
  firewalld:
   port: 80/tcp
   state: enabled
   permanent: yes
   immediate: yes

- name: open service port_
  firewalld:
   port: 443/tcp
   permanent: yes
   state: enabled
   immediate: yes

