---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Add Node.js repository script
  get_url:
   url:  https://rpm.nodesource.com/setup_14.x
   dest: /opt
   mode: 755
- name: Setup Node.js repository
  command: /opt/setup_14.x

- name: Add Nginx Unit repository
  yum_repository:
    name: unit repo
    description: Nginx Unit repo
    baseurl: https://packages.nginx.org/unit/centos/$releasever/$basearch/
    gpgcheck: no
    enabled: yes

- name: Install packages
  yum: 
   name: 
    - "@Development tools"
    - nodejs
    - unit
    - unit-devel
    - git
   state: present 

- name: upgrade all packages
  yum:
   name: '*'
   state: latest
