---
- name: Disable SELinux
  selinux:
   state: disabled

- name: add nginx-plus repo
  yum_repository:
   name: nginx-plus
   description: nginx-plus repo
   baseurl: http://10.4.150.213/nginx-rpms
   gpgcheck: no
   enabled: yes

- name: Install packages
  yum:
   name:
    - epel-release
    - "@Development tools"
    - git
    - nginx-plus 
   state: latest
    
- name: upgrade all packages
  yum:
   name: '*'
   state: latest

- name: open service port 
  firewalld:
   port: '{{ item.port }}'
   permanent: yes
   state: enabled
   immediate: yes
  with_items:
   - { port: '80/tcp' }
   - { port: '443/tcp' }

