---
- name: started and enabled nginx
  service:
   name: nginx
   state: started
   enabled: yes
  
- name: remove older Nginx Config
  file:
   path: /etc/nginx
   state: absent
    
- name: clone new Nginx config
  git:
   repo: https://github.com/MAELUP/loadbalance-dev.git
   dest: /etc/nginx
    
- name: restart nginx
  service:
   name:  nginx
   state: restarted


