---
- name: Disable SELinux
  selinux:
   state: disabled
     
- name: Update /etc/hosts from inventory
  lineinfile:
   dest: /etc/hosts
   regexp: '.*{{item}}$'
   line: '{{ hostvars[item].ansible_default_ipv4.address }}   {{ hostvars[item].ansible_nodename }}'
   state: present
   unsafe_writes: yes
  with_items: '{{ groups.all }}' 

- name: restart network 
  service:
   name: network
   state: restarted

- name: open service port 
  firewalld:
   port: '{{ item.port }}'
   permanent: yes
   state: enabled
   immediate: yes
  with_items:
   - { port: '80/tcp' }
   - { port: '443/tcp' }
