---
- name: Disable SELinux
  selinux:
   state: disabled
     
- name: Update /etc/hosts from inventory
  lineinfile:
   dest: /etc/hosts
   regexp: '.*{{item}}$'
   line: '{{ hostvars[item].ansible_default_ipv4.address }}   {{ hostvars[item].ansible_nodename }}'
   state: present
   unsafe_writes: yes
  with_items: '{{ groups.all }}' 

- name: add virtual ip to /etc/hosts 
  lineinfile:
   dest: /etc/hosts
   regexp: '.*{{ virtual_node_ipaddress }}$'
   line: '{{ virtual_node_ipaddress }}   apigateway.service'
   state: present
   unsafe_writes: yes 

- name: restart network 
  service:
   name: network
   state: restarted


