---
- name: Disable SELinux
  selinux:
   state: disabled

- name: add nginx-plus repo
  yum_repository:
   name: nginx-plus
   description: nginx-plus repo
   baseurl: http://10.4.150.213/nginx-rpms
   gpgcheck: no
   enabled: yes

- name: Install packages
  yum:
   name:
    - "@Development tools"
    - git
    - nginx-plus
    - nginx-plus-module-modsecurity
   state: present

- name: upgrade all packages
  yum:
   name: '*'
   state: latest

- name: Update /etc/hosts from inventory
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{item}}$'
    line: '{{ hostvars[item].ansible_default_ipv4.address }}   {{ hostvars[item].ansible_hostname }}'
    state: present
    unsafe_writes: yes
  with_items: '{{ groups.all }}'

- name: restart network 
  service:
   name: network
   state: restarted